linters:
 flake8:
 eslint:
   config: "stylelint.config.js"
 csslint:
   ignore: 'box-model,box-sizing,important,ids,known-properties,order-alphabetical,empty-rules'
files:
 ignore:
   - "src/generated/*"
   - "webroot/bower_components/*"
